default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: bsc_user
  password: qwerty

development:
  <<: *default
  database: bsc_dev

test:
  <<: *default
  database: bsc_test
