default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: ecomm_user
  password: qwerty

development:
  <<: *default
  database: ecomm_development

test:
  <<: *default
  database: ecomm_test
